xcodeproj 'HZ_iOS_SumTools/HZ_iOS_SumTools.xcodeprj'
platform :ios, '7.0'
target 'HZ_iOS_SumTools' do
pod 'SDWebImage'
pod 'TZImagePickerController', '~> 1.0.4'
pod 'BlocksKit', '~> 2.2.5'
pod 'AFNetworking', '~> 3.0.2'
pod 'XHLaunchAd', '~>2.2.2'
pod 'HcdCachePlayer'
pod 'MJExtension'
end

